CREATE DATABASE IF NOT EXISTS job_tracker;
USE job_tracker;

CREATE TABLE cities(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) UNIQUE);
CREATE TABLE application_status(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) UNIQUE);
CREATE TABLE companies(id INT AUTO_INCREMENT PRIMARY KEY,city_id INT,name VARCHAR(255),website VARCHAR(500),career_url VARCHAR(500),email VARCHAR(255),notes TEXT,FOREIGN KEY(city_id) REFERENCES cities(id));
CREATE TABLE applications(id INT AUTO_INCREMENT PRIMARY KEY,company_id INT,status_id INT,notes TEXT,FOREIGN KEY(company_id) REFERENCES companies(id),FOREIGN KEY(status_id) REFERENCES application_status(id));
INSERT INTO cities(name) VALUES ('Marrakech'),('Agadir'),('Casablanca'),('Rabat'),('Kenitra'),('Tanger');
INSERT INTO application_status(name) VALUES ('Applied'),('Not Applied'),('Technical Problem'),('Interview'),('Rejected'),('Accepted'),('No Response');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'HelloWorld Agency','https://www.helloworld-agency.com','https://www.helloworld-agency.com/recrutement/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (1,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'Energiedin','https://www.energiedin.com','https://www.energiedin.com/agence-digitale-marrakech/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (2,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'Elbahi','https://elbahi.net','https://elbahi.net/offres-demploi/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (3,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'Redbox','https://redbox.ma','https://redbox.ma/carrieres','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (4,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'Klicky','https://www.klicky.ma','https://www.klicky.ma/partenaires','','Technical problem');
INSERT INTO applications(company_id,status_id,notes) VALUES (5,3,'Technical problem');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'iMayWeb','https://www.imayweb.com','https://www.imayweb.com/recrutement','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (6,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'Creative Friends','https://creativefriends.ma','https://creativefriends.ma/contact/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (7,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'Warriors Team','https://www.warriors-team.com','https://www.warriors-team.com/careers','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (8,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'Alamiecom','https://alamiecom.ma','https://alamiecom.ma/recrutement/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (9,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'Nash Digital','https://nash-digital.com','https://nash-digital.com/poste/developpeurs-web/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (10,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'Lightfunnels','','','careers@lightfunnels.com','');
INSERT INTO applications(company_id,status_id,notes) VALUES (11,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (1,'EYSI','','','contact@eysi.net','');
INSERT INTO applications(company_id,status_id,notes) VALUES (12,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (2,'Tweadup','https://tweadup.com','https://tweadup.com/recrutement/','','Technical problem');
INSERT INTO applications(company_id,status_id,notes) VALUES (13,3,'Technical problem');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (2,'Tasyier','https://tasyier.com','https://tasyier.com/carriere/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (14,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (3,'Turnex Agency','https://www.turnexagency.ma','https://www.turnexagency.ma/rejoignez-dream-team/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (15,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (3,'Digital Nova','https://www.digitalnova.ma','https://www.digitalnova.ma/carriere','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (16,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (3,'Smarktic','https://smarktic.com','https://smarktic.com/contacts-01/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (17,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (3,'Digitalma','https://digitalma.ma','https://digitalma.ma/carrieres/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (18,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (3,'EcomGrowth','https://ecomgrowth.fr','https://ecomgrowth.fr/recrutement/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (19,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (3,'XNumerik','https://xnumerik.com','https://xnumerik.com/nous-rejoindre','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (20,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (4,'Nerolink Media','https://nerolinkmedia.com','https://nerolinkmedia.com/carrieres/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (21,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (4,'Wellbek','https://wellbek.com','https://wellbek.com/carriere/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (22,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (4,'Heraz Group','https://www.herazgroup.com','https://www.herazgroup.com/form.php?link=Developpeur','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (23,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (4,'Majjane','https://majjane.ma','https://majjane.ma/fr/carriere/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (24,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (4,'NextMPlus','https://nextmplus.com','https://nextmplus.com/careers/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (25,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (4,'Adkomo','https://www.adkomo.com','https://www.adkomo.com/fr/recrutement/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (26,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (4,'Inovat','https://inovat.ma','https://inovat.ma/fr/careers','','Technical problem');
INSERT INTO applications(company_id,status_id,notes) VALUES (27,3,'Technical problem');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (4,'Edemia','https://www.edemia.fr','https://www.edemia.fr/contactez-nous/','','Not an agency');
INSERT INTO applications(company_id,status_id,notes) VALUES (28,2,'Not an agency');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (5,'GHM Labs','https://ghm-labs.ma','https://ghm-labs.ma/carrieres/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (29,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (5,'Wave Digital','https://wavedigital.agency','https://wavedigital.agency/carrieres#candidature','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (30,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (6,'Rhillane','https://rhillane.com','https://rhillane.com/recrutement/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (31,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (6,'Skyline','','','recrutement@skyline.ma','');
INSERT INTO applications(company_id,status_id,notes) VALUES (32,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (6,'Lahza','https://lahza.ma','https://lahza.ma/recrutement/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (33,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (6,'DevNetCorp','https://devnetcorp.com','https://devnetcorp.com/recrutement/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (34,1,'');
INSERT INTO companies(city_id,name,website,career_url,email,notes) VALUES (6,'Algorite','https://algorite.ma','https://algorite.ma/carriere/','','');
INSERT INTO applications(company_id,status_id,notes) VALUES (35,1,'');
